version: '3'
services:
  config:
    build: config
    ports:
      - 8888:8888
  strava:
    environment:
      - CONFIG_SERVICE_HOST=config
    build: strava
    depends_on:
      - config
    ports:
     - "8000:8000"
